export const FOOTER_UPDATE_REQUEST = 'FOOTER_UPDATE_REQUEST';
export const FOOTER_UPDATE_SUCCESS = 'FOOTER_UPDATE_SUCCESS';
export const FOOTER_UPDATE_FAIL = 'FOOTER_UPDATE_FAIL';
export const FOOTER_UPDATE_RESET = 'FOOTER_UPDATE_RESET';

export const FOOTER_LIST_REQUEST = 'FOOTER_LIST_REQUEST';
export const FOOTER_LIST_SUCCESS = 'FOOTER_LIST_SUCCESS';
export const FOOTER_LIST_FAIL = 'FOOTER_LIST_FAIL';

export const FOOTER_DETAILS_REQUEST = 'FOOTER_DETAILS_REQUEST';
export const FOOTER_DETAILS_SUCCESS = 'FOOTER_DETAILS_SUCCESS';
export const FOOTER_DETAILS_FAIL = 'FOOTER_DETAILS_FAIL';
