export const HIGHLIGHT_UPDATE_REQUEST = 'HIGHLIGHT_UPDATE_REQUEST';
export const HIGHLIGHT_UPDATE_SUCCESS = 'HIGHLIGHT_UPDATE_SUCCESS';
export const HIGHLIGHT_UPDATE_FAIL = 'HIGHLIGHT_UPDATE_FAIL';
export const HIGHLIGHT_UPDATE_RESET = 'HIGHLIGHT_UPDATE_RESET';

export const HIGHLIGHT_LIST_REQUEST = 'HIGHLIGHT_LIST_REQUEST';
export const HIGHLIGHT_LIST_SUCCESS = 'HIGHLIGHT_LIST_SUCCESS';
export const HIGHLIGHT_LIST_FAIL = 'HIGHLIGHT_LIST_FAIL';

export const HIGHLIGHT_DETAILS_REQUEST = 'HIGHLIGHT_DETAILS_REQUEST';
export const HIGHLIGHT_DETAILS_SUCCESS = 'HIGHLIGHT_DETAILS_SUCCESS';
export const HIGHLIGHT_DETAILS_FAIL = 'HIGHLIGHT_DETAILS_FAIL';

export const HIGHLIGHT_CREATE_REQUEST = 'HIGHLIGHT_CREATE_REQUEST';
export const HIGHLIGHT_CREATE_SUCCESS = 'HIGHLIGHT_CREATE_SUCCESS';
export const HIGHLIGHT_CREATE_FAIL = 'HIGHLIGHT_CREATE_FAIL';
export const HIGHLIGHT_CREATE_RESET = 'HIGHLIGHT_CREATE_RESET';

export const HIGHLIGHT_DELETE_REQUEST = 'HIGHLIGHT_DELETE_REQUEST';
export const HIGHLIGHT_DELETE_SUCCESS = 'HIGHLIGHT_DELETE_SUCCESS';
export const HIGHLIGHT_DELETE_FAIL = 'HIGHLIGHT_DELETE_FAIL';
export const HIGHLIGHT_DELETE_RESET = 'HIGHLIGHT_DELETE_RESET';
