export const NAVBAR_UPDATE_REQUEST = 'NAVBAR_UPDATE_REQUEST';
export const NAVBAR_UPDATE_SUCCESS = 'NAVBAR_UPDATE_SUCCESS';
export const NAVBAR_UPDATE_FAIL = 'NAVBAR_UPDATE_FAIL';
export const NAVBAR_UPDATE_RESET = 'NAVBAR_UPDATE_RESET';

export const NAVBAR_LIST_REQUEST = 'NAVBAR_LIST_REQUEST';
export const NAVBAR_LIST_SUCCESS = 'NAVBAR_LIST_SUCCESS';
export const NAVBAR_LIST_FAIL = 'NAVBAR_LIST_FAIL';

export const NAVBAR_DETAILS_REQUEST = 'NAVBAR_DETAILS_REQUEST';
export const NAVBAR_DETAILS_SUCCESS = 'NAVBAR_DETAILS_SUCCESS';
export const NAVBAR_DETAILS_FAIL = 'NAVBAR_DETAILS_FAIL';
